#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

FONT="Iosevka Nerd Font"

##### Bar Appearance #####
sketchybar --bar position=top height=37 blur_radius=0 color=$BAR_COLOR shadow=off

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Bold:15.0"
  label.font="$FONT:Regular:15.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  background.height=24
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
)
sketchybar --default "${default[@]}"

##### Left Side Items #####

source $ITEM_DIR/front_app.sh
source $ITEM_DIR/spaces.sh

##### Center Items #####

source $ITEM_DIR/media.sh

##### Right Side Items #####

source $ITEM_DIR/calendar.sh
source $ITEM_DIR/pomodoro.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh

##### Force all scripts to run the first time #####
sketchybar --update

